use num_derive::FromPrimitive;

use crate::packet::macros::generate_enum_deserialize_impls;

/// All Teams available in F1 2023.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FromPrimitive)]
pub(crate) enum Team {
    Mercedes,
    Prema21,
    Campos22,
    Ferrari,
    UniVirtuosi21,
    VanAmersfoortRacing22,
    RedBullRacing,
    Carlin21,
    Trident22,
    Williams,
    Hitech21,
    Hitech22,
    AstonMartin,
    ArtGP21,
    ArtGP22,
    Alpine,
    MPMotorsport21,
    AlphaTauri,
    Charouz21,
    Haas,
    Dams21,
    McLaren,
    Campos21,
    AlfaRomeo,
    BWT21,
    Mercedes2020,
    Trident21,
    Ferrari2020,
    MercedesAMGGTBlackSeries,
    RedBull2020,
    Mercedes22,
    Williams2020,
    Ferrari22,
    RacingPoint2020,
    RedBullRacing22,
    Renault2020,
    Williams22,
    AlphaTauri2020,
    AstonMartin22,
    Haas2020,
    Alpine22,
    McLaren2020,
    AlphaTauri22,
    AlfaRomeo2020,
    Haas22,
    AstonMartinDB11V12,
    McLaren22,
    AstonMartinVantageF1Edition,
    AlfaRomeo22,
    AstonMartinVantageSafetyCar,
    Konnersport22,
    FerrariF8Tributo,
    Konnersport,
    FerrariRoma,
    Prema22,
    McLaren720S,
    Virtuosi22,
    McLarenArtura,
    Carlin22,
    MercedesAMGGTBlackSeriesSafetyCar,
    MPMotorsport22,
    MercedesAMGGTRPro,
    Charouz22,
    F1Custom,
    Dams22,
}

generate_enum_deserialize_impls!(Team);
